# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxAbdW91lB_ErvAC53J0tCCvO8sweF9x
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from matplotlib.ticker import MaxNLocator

# ------------------ Page config ------------------
st.set_page_config(page_title="World Bank WDI Dashboard", layout="wide")
st.title("🌍 World Bank Development Indicators (1960–2022)")

# ------------------ Load data safely ------------------
try:
    df = pd.read_csv("world_bank_development_indicators.csv")
except FileNotFoundError:
    st.error("world_bank_development_indicators.csv not found! Make sure it is in the root folder.")
    st.stop()

# Clean column names
df.columns = df.columns.str.strip().str.replace('%','pct').str.replace(' ','_')

# Convert 'date' to datetime objects and then extract the year
df['year'] = pd.to_datetime(df['date'], errors='coerce').dt.year

# Drop rows with invalid year
df = df.dropna(subset=['year'])
df['year'] = df['year'].astype(int)

# ------------------ Sidebar filters ------------------
st.sidebar.header("Filters")

countries = st.sidebar.multiselect(
    "Select Countries",
    options=df['country'].unique(),
    default=['United States', 'China', 'India', 'Germany']
)

year_range = st.sidebar.slider(
    "Select Year Range",
    int(df['year'].min()),
    int(df['year'].max()),
    (int(df['year'].min()), int(df['year'].max()))
)

# Apply filters
filtered_df = df.copy()
if countries:
    filtered_df = filtered_df[filtered_df['country'].isin(countries)]
filtered_df = filtered_df[(filtered_df['year'] >= year_range[0]) & (filtered_df['year'] <= year_range[1])]

# ------------------ Helper function ------------------
def five_year_ticks(ax):
    ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=12))
    plt.xticks(rotation=45)

# ------------------ Layout ------------------
st.sidebar.markdown("Select one question at a time from below.")
question = st.sidebar.selectbox(
    "Choose Question",
    [
        "Q1 Global GDP",
        "Q2 Wealth vs Health",
        "Q3 CO₂ Emitters",
        "Q4 Renewable Energy",
        "Q5 Electricity Access",
        "Q6 Education & HCI",
        "Q7 Birth & Death Rates",
        "Q8 Internet Divide",
        "Q9 Governance & Stability",
        "Q10 Land Use",
        "Q11 Military Spending",
        "Q12 Inflation",
        "Q13 Health Spending",
        "Q14 Safety & Wealth",
        "Q15 R&D & GDP"
    ]
)

# ------------------ Q1 Global GDP ------------------
if question == "Q1 Global GDP":
    gdp = filtered_df.groupby('year')['GDP_current_US'].sum().reset_index()
    st.line_chart(gdp.set_index('year'))

# ------------------ Q2 Wealth vs Health ------------------
elif question == "Q2 Wealth vs Health":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='GDP_per_capita',
        y='Life_expectancy',
        hue='country',
        ax=ax
    )
    ax.set_title("GDP per Capita vs Life Expectancy")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q3 CO₂ Emitters ------------------
elif question == "Q3 CO₂ Emitters":
    latest = filtered_df[filtered_df['year'] == filtered_df['year'].max()]
    top_emitters = latest.sort_values('CO2_emisions', ascending=False).head(10)
    fig, ax = plt.subplots()
    sns.barplot(
        data=top_emitters,
        x='CO2_emisions',
        y='country',
        palette=sns.color_palette("Reds_r", len(top_emitters)),
        ax=ax
    )
    ax.set_title("Top 10 CO₂ Emitters")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q4 Renewable Energy ------------------
elif question == "Q4 Renewable Energy":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='renewable_energy_consumptionpct',
        hue='country',
        ax=ax
    )
    ax.set_title("Renewable Energy Consumption (%)")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q5 Electricity Access ------------------
elif question == "Q5 Electricity Access":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='rural_population',
        y='access_to_electricitypct',
        hue='country',
        ax=ax
    )
    ax.set_title("Rural Population vs Access to Electricity (%)")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q6 Education & HCI ------------------
elif question == "Q6 Education & HCI":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='mean_years_schooling',
        y='Human_capital_index',
        hue='country',
        ax=ax
    )
    ax.set_title("Education vs Human Capital Index")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q7 Birth & Death Rates ------------------
elif question == "Q7 Birth & Death Rates":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='birth_rate',
        hue='country',
        ax=ax,
        linestyle='-'
    )
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='death_rate',
        hue='country',
        ax=ax,
        linestyle='--',
        legend=False
    )
    ax.set_title("Birth & Death Rates Over Time")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q8 Internet Divide ------------------
elif question == "Q8 Internet Divide":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='internet_users_per_100',
        y='GDP_per_capita',
        hue='country',
        ax=ax
    )
    ax.set_title("Internet Users vs GDP per Capita")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q9 Governance & Stability ------------------
elif question == "Q9 Governance & Stability":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='Government_effectiveness',
        y='Political_stability',
        hue='country',
        ax=ax
    )
    ax.set_title("Governance & Political Stability")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q10 Land Use ------------------
elif question == "Q10 Land Use":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='arable_landpct',
        hue='country',
        ax=ax
    )
    ax.set_title("Arable Land (%) Over Time")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q11 Military Spending ------------------
elif question == "Q11 Military Spending":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='Military_expenditure_pct_GDP',
        hue='country',
        ax=ax
    )
    ax.set_title("Military Expenditure (% of GDP)")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q12 Inflation ------------------
elif question == "Q12 Inflation":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='Inflation_rate',
        hue='country',
        ax=ax
    )
    ax.set_title("Inflation Rate Over Time")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q13 Health Spending ------------------
elif question == "Q13 Health Spending":
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x='year',
        y='Health_expenditure_pct_GDP',
        hue='country',
        ax=ax
    )
    ax.set_title("Health Expenditure (% of GDP)")
    five_year_ticks(ax)
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q14 Safety & Wealth ------------------
elif question == "Q14 Safety & Wealth":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='GDP_per_capita',
        y='Intentional_homicides_per_100k',
        hue='country',
        ax=ax
    )
    ax.set_title("GDP per Capita vs Homicides")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Q15 R&D & GDP ------------------
elif question == "Q15 R&D & GDP":
    fig, ax = plt.subplots()
    sns.scatterplot(
        data=filtered_df[filtered_df['year'] == filtered_df['year'].max()],
        x='R&D_expenditure_pct_GDP',
        y='GDP_per_capita',
        hue='country',
        ax=ax
    )
    ax.set_title("R&D Expenditure vs GDP per Capita")
    st.pyplot(fig)
    plt.close(fig)

# ------------------ Insights ------------------
st.markdown("### 📌 Key Insights")
st.markdown("""
- GDP, CO₂, and energy patterns vary significantly by country and over time.
- Higher GDP per capita usually correlates with higher life expectancy.
- Renewable energy adoption is growing in major economies but at different rates.
- Access to electricity, internet, and health spending highlight global inequalities.
- Governance, political stability, and safety indicators show the relationship between wealth and social outcomes.
""")

